### ISSUE TITLE
RCD_CAR - test connection

### ISSUE THREAD

**Issue by lorenzoMacca** [lorenzoMacca/RCD_demo#2]
implement the test connection.
arduino sends AT and the ESP8266 module has to reply with "OK"

**Comment by F-Nietzsche** [comment]
Lo ho provato la lib e lo sketch che mi hai fornito, ma non va... ho fatto lo screen e l'ho messo nella cartella principale qui (errore.png).Provalo tu mi sa che la mia scheda e diversa e non va bene.
Non si potrebbe fare qualcosa a livello di  comandi AT al posto di utilizzare l'apposita libreria?

**Comment by lorenzoMacca** [comment]
Ciao Sax,
la libreria andrá ad utilizzare i comandi AT.
Attualmente il modulo funziona se si inviano i messaggi AT lungo il monitor seriale di arduino + le porte TX e RX. Arduino Uno ha purtroppo un solo seriale esclusivo, questo significa che puó essere utilizzato da un solo modulo alla volta. Un modo per collegare altri moduli é quella di utilizzare softwareserial.h la quale simula via software un altro seriale.
- lorenzo

**Comment by lorenzoMacca** [comment]
Il primo test usando #include <SoftwareSerial.h> é stato positivo.
Inviando il mess AT+RST il modulo risponde in modo corretto.

Dichiarare un altro seriale
`SoftwareSerial mySerial(10, 11); // RX, TX`

dichiare i pin di I/O
`pinMode(10, INPUT);
  pinMode(11, OUTPUT);`

testare il modulo
`Serial.println("TEST ESP8266");
  mySerial.begin(115200);
  mySerial.readString();
  mySerial.println("AT");
  Serial.println(mySerial.readString());
  Serial.println("FINE");`

**Comment by lorenzoMacca** [comment]
il modulo ESP8266 risponde correttamente al mess AT, il problema sta ora nel sniffare correttamente il messaggio OK inviato dal modulo

**Comment by lorenzoMacca** [comment]
la funzione test connection e' stata sviluppata... ora la sto testando.

**Comment by F-Nietzsche** [comment]
ma non ho capito una cosa il tx e rx del modulo vanno connessi ai pin 10 e 11?
E i pin 0 e 1 non utilizzati?

**Comment by F-Nietzsche** [comment]
compilando solamente mi da errore alla riga:
 esp8266 = new ESP8266Arduino(&esp8266Serial, &Serial);

**Comment by lorenzoMacca** [comment]
Si devi usare i pin 10 e 11

**Comment by lorenzoMacca** [comment]
Posta l errore completo, quello che dà il compilatore

**Comment by F-Nietzsche** [comment]
sketch_may03c:15: error: no matching function for call to 'ESP8266Arduino::ESP8266Arduino(SoftwareSerial_, HardwareSerial_)'

   esp8266 = new ESP8266Arduino(&esp8266Serial, &Serial);

```
                                                   ^
```

C:\Users\salvatore\Documents\Arduino\sketch_may03c\sketch_may03c.ino:15:55: note: candidates are:

In file included from C:\Users\salvatore\Documents\Arduino\sketch_may03c\sketch_may03c.ino:1:0:

C:\Users\salvatore\Documents\Arduino\libraries\ESP8266/ESP8266Arduino.h:24:3: note: ESP8266Arduino::ESP8266Arduino(Stream*)

   ESP8266Arduino(Stream *serial);

   ^

C:\Users\salvatore\Documents\Arduino\libraries\ESP8266/ESP8266Arduino.h:24:3: note:   candidate expects 1 argument, 2 provided

C:\Users\salvatore\Documents\Arduino\libraries\ESP8266/ESP8266Arduino.h:14:7: note: constexpr ESP8266Arduino::ESP8266Arduino(const ESP8266Arduino&)

 class ESP8266Arduino{

```
   ^
```

C:\Users\salvatore\Documents\Arduino\libraries\ESP8266/ESP8266Arduino.h:14:7: note:   candidate expects 1 argument, 2 provided

Più di una libreria trovata per "ESP8266Arduino.h"
Usata: C:\Users\salvatore\Documents\Arduino\libraries\ESP8266
Non usata: C:\Users\salvatore\Desktop\arduino-nightly\libraries\ESP8266
exit status 1
no matching function for call to 'ESP8266Arduino::ESP8266Arduino(SoftwareSerial_, HardwareSerial_)'

**Comment by F-Nietzsche** [comment]
Dici che è un prob. della lib?

**Comment by F-Nietzsche** [comment]
Funziona

**Comment by F-Nietzsche** [comment]
Leggo questo a monitor seriale
fuck...
Test connection
fuck...

**Comment by lorenzoMacca** [comment]
Ok significa che al messaggio AT non ricevi la risposta ok da parte del modulo.  Ricorda di collegare RX del modulo con TX di arduino... Hai provato?

**Comment by lorenzoMacca** [comment]
![](http://i.imgur.com/prIobM0.jpg)

**Comment by F-Nietzsche** [comment]
Test connection
connection OK

Finalmente funge....
